server:
  port: 9001
spring:
  application:
    name: anl_testdemo
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/anl?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  jpa:
    database: MySQL
    show-sql: true

